### ISSUE TITLE
there are no files

### ISSUE THREAD

**Issue by iamdenny** [linnovate/mean-admin#26]
I've just install as 'mean init test' and selected 'mean-admin'
and then start 'node server'.
I got some errors below.
packages/contrib/mean-admin/public/assets/css/themes.css not found
packages/contrib/mean-admin/public/assets/js/users.js not found
and some more

please check the files.

**Comment by brownman** [comment]
[nodemon] watching: *.*
[nodemon] starting `node --debug server.js`
debugger listening on port 5858
/home/someone1/MEAN_NETWORK/NETWORK/mean_with_admin_panel/packages/contrib/mean-admin/public/assets/css/themes.css not found
/home/someone1/MEAN_NETWORK/NETWORK/mean_with_admin_panel/packages/contrib/mean-admin/public/assets/js/users.js not found
/home/someone1/MEAN_NETWORK/NETWORK/mean_with_admin_panel/packages/contrib/mean-admin/public/assets/js/themes.js not found
/home/someone1/MEAN_NETWORK/NETWORK/mean_with_admin_panel/packages/contrib/mean-admin/public/assets/js/modules.js not found
/home/someone1/MEAN_NETWORK/NETWORK/mean_with_admin_panel/packages/contrib/mean-admin/public/assets/js/ng-clip.js not found
/home/someone1/MEAN_NETWORK/NETWORK/mean_with_admin_panel/packages/contrib/mean-admin/public/assets/js/settings.js not found
Mean app started on port 3000 (development) cluster.worker.id: 0

**Comment by petersandor** [comment]
Same happened to me just now (Windows 7, freshly installed Mean - 0.4.3).

λ node server
for real!
forking  0
forking  1
forking  2
forking  3
C:\testapp-mean\packages\contrib\mean-admin\public\assets\css\themes.css not found
C:\testapp-mean\packages\contrib\mean-admin\public\assets\js\users.js not found
C:\testapp-mean\packages\contrib\mean-admin\public\assets\js\themes.js not found
C:\testapp-mean\packages\contrib\mean-admin\public\assets\js\modules.js not found
C:\testapp-mean\packages\contrib\mean-admin\public\assets\js\ng-clip.js not found
C:\testapp-mean\packages\contrib\mean-admin\public\assets\js\settings.js not found
C:\testapp-mean\packages\contrib\mean-admin\public\assets\css\themes.css not found
C:\testapp-mean\packages\contrib\mean-admin\public\assets\js\users.js not found
C:\testapp-mean\packages\contrib\mean-admin\public\assets\js\themes.js not found
C:\testapp-mean\packages\contrib\mean-admin\public\assets\js\modules.js not found
C:\testapp-mean\packages\contrib\mean-admin\public\assets\js\ng-clip.js not found
C:\testapp-mean\packages\contrib\mean-admin\public\assets\js\settings.js not found
C:\testapp-mean\packages\contrib\mean-admin\public\assets\css\themes.css not found
C:\testapp-mean\packages\contrib\mean-admin\public\assets\js\users.js not found
C:\testapp-mean\packages\contrib\mean-admin\public\assets\js\themes.js not found
C:\testapp-mean\packages\contrib\mean-admin\public\assets\js\modules.js not found
C:\testapp-mean\packages\contrib\mean-admin\public\assets\js\ng-clip.js not found
C:\testapp-mean\packages\contrib\mean-admin\public\assets\js\settings.js not found
C:\testapp-mean\packages\contrib\mean-admin\public\assets\css\themes.css not found
C:\testapp-mean\packages\contrib\mean-admin\public\assets\js\users.js not found
C:\testapp-mean\packages\contrib\mean-admin\public\assets\js\themes.js not found
C:\testapp-mean\packages\contrib\mean-admin\public\assets\js\modules.js not found
C:\testapp-mean\packages\contrib\mean-admin\public\assets\js\ng-clip.js not found
C:\testapp-mean\packages\contrib\mean-admin\public\assets\js\settings.js not found
Mean app started on port 3000 (development) cluster.worker.id: 4
Mean app started on port 3000 (development) cluster.worker.id: 2
Mean app started on port 3000 (development) cluster.worker.id: 3
Mean app started on port 3000 (development) cluster.worker.id: 1

**Comment by MarcosRZ** [comment]
Same problem as @petersandor but (mean 0.9.20, ubuntu 14.10).

**Comment by telldrak** [comment]
This issue stems from lines 15-21 of /packages/mean-admin/app.js:

    Admin.aggregateAsset('css', 'admin.css');
    Admin.aggregateAsset('css', 'themes.css');
    Admin.aggregateAsset('js', 'users.js');
    Admin.aggregateAsset('js', 'themes.js');
    Admin.aggregateAsset('js', 'modules.js');
    Admin.aggregateAsset('js', 'ng-clip.js');
    Admin.aggregateAsset('js', 'settings.js');

There is no js folder in /packages/mean-admin/public/assets/ and no themes.css file in the css folder.

**Comment by oritpersik** [comment]
fixed.

**Comment by twohue** [comment]
Thank you!
